# Generated by Django 3.1 on 2020-11-28 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedBy',
            field=models.ManyToManyField(related_name='likedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
