# Generated by Django 3.1 on 2020-11-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likedBy',
        ),
    ]
