# Generated by Django 3.1 on 2020-12-04 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201128_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ManyToManyField(default={}, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='following',
            field=models.ManyToManyField(default={}, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
